name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: use Node.js
        uses: actions/setup-node@v4

      - name: clean install dependencies
        run: npm ci

      - name: run tests
        run: npm test